classifier: svm
eval_window_size: 1
feats: tfidf
feats_window_size: 5
max_features: 5000
strategy: weights
test_range_max: 100
text_features: select
train_range_max: 100
weights_type: window
weights_window_size: 100
