feats_window_size: 10  #default: 1
eval_window_size: 1  #default: 5
max_features: 5000   #default: 5000
feats: "text"  #text, tfidf, ngram, combined
classifier: "xgboost" #svm, linear_svm, forest, xgboost, bayes
strategy: "balanced"